In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
train = pd.read_csv('train.csv')
train.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [22]:
train.shape

(20800, 5)

In [23]:
test = pd.read_csv('test.csv')
test.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [24]:
test.shape

(5200, 4)

In [25]:
Test_id = test["id"]

In [26]:
test.isnull().sum()

id          0
title     122
author    503
text        7
dtype: int64

In [27]:
train.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [28]:
train = train.dropna()

In [29]:
train.shape

(18285, 5)

In [30]:
train = train.reset_index()

In [31]:
x = train['title']
y = train['label']

In [32]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [33]:
review1 = train['title'][0]
review1

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [34]:
review1 = re.sub('[^a-zA-Z]', ' ', review1)
review1

'House Dem Aide  We Didn t Even See Comey s Letter Until Jason Chaffetz Tweeted It'

In [35]:
review1 = review1.lower()
review1

'house dem aide  we didn t even see comey s letter until jason chaffetz tweeted it'

In [36]:
review1 = review1.split()
review1

['house',
 'dem',
 'aide',
 'we',
 'didn',
 't',
 'even',
 'see',
 'comey',
 's',
 'letter',
 'until',
 'jason',
 'chaffetz',
 'tweeted',
 'it']

In [37]:
ps = PorterStemmer()
review1 = [ps.stem(word) for word in review1 if not word in stopwords.words('english')] 
review1

['hous',
 'dem',
 'aid',
 'even',
 'see',
 'comey',
 'letter',
 'jason',
 'chaffetz',
 'tweet']

In [38]:
review1 = ' '.join(review1)
review1

'hous dem aid even see comey letter jason chaffetz tweet'

In [39]:
ps = PorterStemmer()
corpus = []
for i in range(0, len(train)):
    review = re.sub('[^a-zA-Z]', ' ', train['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [40]:
voc_size = 5000

In [41]:
from tensorflow.keras.preprocessing.text import one_hot

In [42]:
one_hot_rep = [one_hot(words, voc_size) for words in corpus] 

In [43]:
one_hot_rep

[[3701, 3549, 4057, 4942, 717, 218, 100, 4303, 2149, 3579],
 [4340, 1791, 4364, 3827, 4078, 4497, 4071],
 [4465, 3129, 1977, 4266],
 [698, 3694, 2977, 554, 1921, 3073],
 [591, 4078, 1444, 1265, 1743, 1493, 4078, 227, 2318, 2766],
 [4619,
  1114,
  815,
  18,
  3864,
  1383,
  3561,
  2777,
  4838,
  2903,
  3318,
  4405,
  4604,
  4236,
  4071],
 [542, 892, 613, 2675, 1319, 2672, 2517, 4282, 3714, 1719, 3590],
 [2438, 1740, 1246, 708, 4880, 1074, 1383, 4186, 3714, 1719, 3590],
 [2831, 4484, 2266, 3537, 2536, 3046, 4449, 4375, 1383, 2938],
 [3720, 2479, 1141, 4704, 1031, 1822, 4691, 2959],
 [184, 4356, 1260, 1259, 1740, 3476, 4867, 4119, 1065, 3482, 1254],
 [554, 2946, 717, 3046, 1383, 4880],
 [109, 1681, 1557, 3568, 2497, 2953, 4429, 2594, 4951],
 [2, 3271, 1748, 296, 4626, 4609, 2067, 3714, 1719, 3590],
 [2665, 2832, 1097, 4806, 1958, 3714, 1719, 3590],
 [1031, 1020, 60, 629, 1755, 1322, 3438, 2709, 4982, 3390],
 [4419, 4318, 1791],
 [3749, 1091, 1661, 4446, 1383, 2415, 3102, 4071],
 

In [44]:
len(one_hot_rep[0])

10

In [45]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [47]:
sentence_length = 25

In [48]:
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen = sentence_length)
print(embedded_docs)

[[   0    0    0 ... 4303 2149 3579]
 [   0    0    0 ... 4078 4497 4071]
 [   0    0    0 ... 3129 1977 4266]
 ...
 [   0    0    0 ... 3714 1719 3590]
 [   0    0    0 ... 4451 1264 2247]
 [   0    0    0 ... 3166 1316 4694]]


In [49]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [50]:
embedding_vector_features = 40
model=Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = sentence_length))
model.add(Dropout(0.3))
model.add(LSTM(200))
model.add(Dropout(0.3))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [51]:
x =np.array(embedded_docs)
y =np.array(y)

In [52]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.10, random_state = 42)

In [53]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=20,batch_size=64)

Train on 16456 samples, validate on 1829 samples
Epoch 1/20
16456/16456 [==============================] - 16s 970us/sample - loss: 0.2979 - accuracy: 0.8618 - val_loss: 0.2087 - val_accuracy: 0.9081
Epoch 2/20
16456/16456 [==============================] - 13s 808us/sample - loss: 0.1436 - accuracy: 0.9443 - val_loss: 0.2181 - val_accuracy: 0.9081
Epoch 3/20
16456/16456 [==============================] - 14s 881us/sample - loss: 0.1081 - accuracy: 0.9579 - val_loss: 0.2422 - val_accuracy: 0.9005
Epoch 4/20
16456/16456 [==============================] - 14s 828us/sample - loss: 0.0785 - accuracy: 0.9717 - val_loss: 0.3176 - val_accuracy: 0.9098
Epoch 5/20
16456/16456 [==============================] - 13s 807us/sample - loss: 0.0604 - accuracy: 0.9776 - val_loss: 0.3337 - val_accuracy: 0.9032
Epoch 6/20
16456/16456 [==============================] - 13s 768us/sample - loss: 0.0453 - accuracy: 0.9837 - val_loss: 0.3548 - val_accuracy: 0.9010
Epoch 7/20
16456/16456 [=====================

In [54]:
test = test.drop(['text','id','author'], axis = 1)

In [55]:
test = test.fillna('fake fake fake')

In [56]:
ps = PorterStemmer()
corpus_test = []
for i in range(0, len(test)):
    review = re.sub('[^a-zA-Z]', ' ',test['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus_test.append(review)

In [57]:
one_hot_rep_Test = [one_hot(words, voc_size) for words in corpus_test] 

In [58]:
sentence_length = 25

In [59]:
embedded_docs_test = pad_sequences(one_hot_rep_Test, padding='pre', maxlen = sentence_length)
print(embedded_docs_test)

[[   0    0    0 ... 3714 1719 3590]
 [   0    0    0 ... 1594 2594 3988]
 [   0    0    0 ... 1257  640 3186]
 ...
 [   0    0    0 ... 3714 1719 3590]
 [   0    0    0 ...  184 1587 4754]
 [   0    0    0 ... 3714 1719 3590]]


In [60]:
x_test = np.array(embedded_docs_test)

In [61]:
pred = model.predict_classes(x_test)

In [62]:
val=[]
for i in pred:
    val.append(i[0])

In [63]:
solution = pd.DataFrame({'id': Test_id, 'label': val})
solution.to_csv('Demo.csv', index = False)